name: deploy_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jinja2==2.10.1
  - lektor==3.1.3
  - mistune==0.8.4
  - werkzeug==0.16.0
  - pip
  - pip:
    - git+https://github.com/baldwint/lektor-jupyter.git
